
ALTER TABLE Service ADD telephone VARCHAR(20) NULL;
ALTER TABLE NAF_N5 ADD temEnServNAF_N5 VARCHAR(1) NULL DEFAULT 'O';
ALTER TABLE NAF_N1 ADD temEnServNAF_N1 VARCHAR(1) NULL DEFAULT 'O';
ALTER TABLE Avenant ADD monnaieGratification VARCHAR(50) NULL DEFAULT 'euros';